name: Update README metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate metrics card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Istanbul

      - name: Generate introduction card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          filename: metrics.plugin.introduction.svg
          base: ""
          plugin_introduction: yes

      - name: Generate trophy card
        uses: soulteary/github-profile-trophy-action@v1.0.0
        with:
          options: 'username=${{ github.repository_owner }}&theme=gruvbox&column=7&margin-w=15&margin-h=15&rank=SECRET,SSS,SS,S,AAA,AA,A'
          path: profile/trophy.svg
          token: ${{ secrets.METRICS_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-metrics.svg metrics.plugin.introduction.svg profile/trophy.svg
          git commit -m "Update README metrics" || exit 0
          git push
